---
abstract: 'A PoCo-IRC plugin which prints'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-RTorrentStatus
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0
  DateTime::Duration: 0
  DateTime::Format::Human::Duration: 0
  Format::Human::Bytes: 0
  List::Util: 0
  POE: 1.287
  POE::Component::IRC: 0
  POE::Component::IRC::Plugin::FollowTail: 6.22
resources:
  Ratings: http://cpanratings.perl.org/d/POE-Component-IRC-Plugin-RTorrentStatus
  bugtracker: http://github.com/hinrik/poe-component-irc-plugin-rtorrentstatus/issues
  homepage: http://search.cpan.org/dist/POE-Component-IRC-Plugin-RTorrentStatus
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/poe-component-irc-plugin-rtorrentstatus.git
version: 0.03
